version: '3.7'

services:
  domains:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.domains.entrypoints=https"
      - "traefik.http.routers.domains.rule=HostRegexp(`domains`)"
      - "traefik.http.routers.domains.tls=true"
      - "traefik.http.routers.domains.tls.certresolver=le"
      - "traefik.http.routers.domains.tls.domains[0].main=kitt.run"
      - "traefik.http.routers.domains.tls.domains[0].sans=*.kitt.run"
      - "traefik.http.routers.domains.tls.domains[1].sans=*.whoa.bot"
      - "traefik.http.routers.domains.tls.domains[2].sans=*.eldri.ch"
      - "traefik.http.routers.domains.tls.domains[3].sans=*.defn.sh"
      - "traefik.http.routers.domains.tls.domains[4].sans=*.defn.in"
      - "traefik.http.routers.domains.tls.domains[5].sans=*.defn.jp"
  hello:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=HostRegexp(`hello.{domain:.+}`)"
  hello-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/hello.hcl
      CENTRAL_CONFIG: /central_config/hello.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "hello"]
    network_mode: "service:hello"
  goodbye:
    image: nginx
    networks:
      default:
        ipv4_address: 172.31.188.202
  goodbye-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/goodbye.hcl
      SERVICE_PROXY_CONFIG: /config/goodbye-proxy.hcl
      CENTRAL_CONFIG: /central_config/goodbye.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "goodbye"]
    network_mode: "service:goodbye"

networks:
  default:
    external:
      name: kitt
