version: '3.7'

services:
  whoami:
    image: containous/whoami
    labels:
      - "zone=kitt"
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=http,https"
      - "traefik.http.routers.api.rule=HostRegexp(`whoami.{domain:.+}`)"

networks:
  default:
    external:
      name: kitt_default
