version: '3.7'

services:
  api:
    image: nginx
    restart: always
    volumes:
      - api:/usr/share/nginx/html
      - api_nginx:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.rule=PathPrefix(`/bastion-1/jojomomojo/`)"
  hello:
    image: nginx
    restart: always
    volumes:
      - hello:/usr/share/nginx/html
      - hello_nginx:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=HostRegexp(`hello.{domain:.+}`)"
  goodbye:
    image: nginx
    restart: always
    volumes:
      - goodbye:/usr/share/nginx/html

volumes:
  api:
  api_nginx:
  hello:
  hello_nginx:
  goodbye:

networks:
  default:
    external:
      name: kitt
