version: '3.7'

services:
  apex:
    image: nginx
    restart: always
    volumes:
      - apex:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apex.entrypoints=https"
      - "traefik.http.routers.apex.rule=Host(`${KITT_DOMAIN}`)"
  hello:
    image: nginx
    restart: always
    volumes:
      - hello:/usr/share/nginx/html
      - hello_nginx:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=HostRegexp(`hello.{domain:.+}`)"
  hello-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/hello.hcl
      CENTRAL_CONFIG: /central_config/hello.hcl
    volumes:
      - hello_proxy_config:/config
      - hello_proxy_central:/central_config
    command: ["consul", "connect", "envoy","-sidecar-for", "hello"]
    network_mode: "service:hello"
  goodbye:
    image: nginx
    restart: always
    volumes:
      - goodbye:/usr/share/nginx/html
  goodbye-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/goodbye.hcl
      SERVICE_PROXY_CONFIG: /config/goodbye-proxy.hcl
      CENTRAL_CONFIG: /central_config/goodbye.hcl;/central_config/goodbye-resolver.hcl
    volumes:
      - goodbye_proxy_config:/config
      - goodbye_proxy_central:/central_config
    command: ["consul", "connect", "envoy","-sidecar-for", "goodbye"]
    network_mode: "service:goodbye"

volumes:
  apex:
  hello:
  hello_nginx:
  hello_proxy_config:
  hello_proxy_central:
  goodbye:
  goodbye_proxy_config:
  goodbye_proxy_central:

networks:
  default:
    external:
      name: kitt
