version: '3.7'

services:
  whoami:
    image: containous/whoami
    labels:
      - "SERVICE_NAME=whoami"
      - "zone=kitt"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=http,https"
      - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.{domain:.+}`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80" 
    ports:
      - 80

networks:
  default:
    external:
      name: kitt_default
