version: '3.7'

services:
  zt:
    image: nginx
    restart: always
    volumes:
      - "./html/zt:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zt.entrypoints=https"
      - "traefik.http.routers.zt.rule=Host(`${KITT_DOMAIN}`)"
  hello:
    image: nginx
    restart: always
    volumes:
      - "./html/hello:/usr/share/nginx/html"
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=HostRegexp(`hello.{domain:.+}`)"
  hello-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/hello.hcl
      CENTRAL_CONFIG: /central_config/hello.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "hello"]
    network_mode: "service:hello"
  goodbye:
    image: nginx
    restart: always
    volumes:
      - "./html/goodbye:/usr/share/nginx/html"
    networks:
      default:
        ipv4_address: 172.31.188.202
  goodbye-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/goodbye.hcl
      SERVICE_PROXY_CONFIG: /config/goodbye-proxy.hcl
      CENTRAL_CONFIG: /central_config/goodbye.hcl;/central_config/goodbye-resolver.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "goodbye"]
    network_mode: "service:goodbye"

networks:
  default:
    external:
      name: kitt
