version: '3.7'

services:
  apex:
    image: nginx
    restart: always
    volumes:
      - apex:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apex.entrypoints=https"
      - "traefik.http.routers.apex.rule=Host(`${KITT_DOMAIN}`)"
  hello:
    image: nginx
    restart: always
    volumes:
      - hello:/usr/share/nginx/html
      - hello_nginx:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=HostRegexp(`hello.{domain:.+}`)"
  goodbye:
    image: nginx
    restart: always
    volumes:
      - goodbye:/usr/share/nginx/html

volumes:
  apex:
  hello:
  hello_nginx:
  goodbye:

networks:
  default:
    external:
      name: kitt
