version: '3.7'

services:
  domains:
    image: nginx
  hello:
    image: nginx
  hello-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/hello.hcl
      CENTRAL_CONFIG: /central_config/hello.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "hello"]
    network_mode: "service:hello"
  goodbye:
    image: nginx
    networks:
      default:
        ipv4_address: 172.31.188.202
  goodbye-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      SERVICE_CONFIG: /config/goodbye.hcl
      SERVICE_PROXY_CONFIG: /config/goodbye-proxy.hcl
      CENTRAL_CONFIG: /central_config/goodbye.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "goodbye"]
    network_mode: "service:goodbye"
